Add eth-fox strategy for ShapeShift Fox Farm
pickle-finance/protocol pull request #87
Opened 2021-07-30 02:36 UTC by yiepier

- ShapeShift FoxFarm base strategy
- Fox-Eth lp strategy
- Waffle unit test

2021-08-01 07:53 UTC, janklimo commented on src/strategies/strategy-fox-farm-base.sol
> +            uint256 _keepFOX = _fox.mul(keepFOX).div(keepFOXMax);
Would it be 0% given `keepFOX` value?

2021-08-02 12:45 UTC, abiencode requested changes

2021-08-03 14:28 UTC, yiepier commented on src/strategies/strategy-fox-farm-base.sol
> +            uint256 _keepFOX = _fox.mul(keepFOX).div(keepFOXMax);
yes

2021-08-06 03:13 UTC, abiencode approved these changes

2021-08-10 08:30 UTC, merged